enum {ID_BUTTON_CONNECT, ID_FILE_ABOUT, ID_FILE_OPEN,ID_FILE_IMPORT,ID_FILE_SAVE,ID_FILE_SAVEAS, BUTTON_ID_READ , BUTTON_ID_WRITE, BUTTON_ID_VERIFY, BUTTON_ID_DONE, BUTTON_ID_SETROT, BUTTON_ID_SETANIM, CHOICE_ID_MIRROR, ID_PORTTYPE_SERIAL, ID_PORTTYPE_PARALLEL, ID_PORTTYPEMENU, ID_PORTMENU, ID_WHEELSIZEMENU, ID_WHEELSIZE_BMX, ID_WHEELSIZE_ROAD, ID_HUBSIZE, ID_COMMDELAY, ID_PORTTYPE_USB, ID_TESTPORT, ID_PORT_LPT1, ID_PORT_LPT2, ID_PORT_LPT3, ID_PORT_SERIAL};

enum { NONE, DRAWING, ERASING, IMAGEFOLLOW, IMAGEMOVE, IMAGERESIZE_NW, IMAGERESIZE_SE, IMAGERESIZE_SW, IMAGERESIZE_NE };

#define TABSIZE 10 // the size of the square resizing tabs
#define ROWS_PER_WHEEL 256
#define PI 3.141592

#define EEPROM_ANIMTIME 0x8002
#define EEPROM_ROTOFFSET 0x8000
#define EEPROM_MIRROR 0x8001
